Convert the project to Swift 3.0 Xcode 8 b6
tomkowz/NetworkLayerExample pull request #2
Opened 2016-08-25 09:52 UTC by darthpelo

2016-08-25 09:53 UTC, darthpelo commented
Hi @tomkowz fell free to merge when Swift 3.0 will be official :)

2016-08-25 15:02 UTC, tomkowz commented
Hi @darthpelo, thank you for your contribution. Great work!

2016-09-18 11:38 UTC, Fawxy commented on Network/NetworkOperation.swift
>      private var _ready: Bool
Should be `_isReady`

2016-09-18 11:38 UTC, Fawxy commented on Network/NetworkOperation.swift
>      private var _executing: Bool
Should be `_isExecuting`

2016-09-18 11:38 UTC, Fawxy commented on Network/NetworkOperation.swift
>      private var _finished: Bool
Should be `_isFinished`

2016-09-18 11:39 UTC, Fawxy commented on Network/NetworkOperation.swift
>          set { update({ self._ready = newValue }, key: "isReady") }
Should be `update(change:`

2016-09-18 11:39 UTC, Fawxy commented on Network/NetworkOperation.swift
>          set { update({ self._executing = newValue }, key: "isExecuting") }
Should be `update(change:`

2016-09-18 11:39 UTC, Fawxy commented on Network/NetworkOperation.swift
>          set { update({ self._finished = newValue }, key: "isFinished") }
Should be `update(change:`

2016-09-18 11:40 UTC, Fawxy commented on Network/NetworkOperation.swift
>          set { update({ self._cancelled = newValue }, key: "isCancelled") }
Should be `update(change:`

2016-09-18 11:40 UTC, Fawxy commented on Network/NetworkOperation.swift
>      private var _cancelled: Bool
Should be `_isCancelled`

2016-09-18 11:41 UTC, Fawxy commented on Network/NetworkService.swift
>          case GET, POST, PUT, DELETE
Enum should be lowercase

2016-09-18 11:41 UTC, Fawxy commented on Network/NetworkService.swift
> +        case JSON, PATH
Enum should be lowercase

2016-09-18 11:44 UTC, Fawxy commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
Should return a `URLRequest`

2016-09-18 11:44 UTC, Fawxy commented on Network/NetworkService.swift
> +            let mutableRequest = NSMutableURLRequest(url: url, cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
should be `var mutableRequest = URLRequest(url:`

2016-09-18 11:45 UTC, Fawxy commented on Network/NetworkService.swift
> +            return NSMutableURLRequest(url: comp.url!, cachePolicy: .reloadIgnoringLocalAndRemoteCacheData, timeoutInterval: 10.0)
Should be `URLRequest(url:`

2016-09-18 11:48 UTC, Fawxy requested changes
Few things to make this properly Swift 3-ified. Should also be noted that `JSONSerialization` now returns `Any` rather than `AnyObject`.

2016-09-18 17:12 UTC, tomkowz commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
Later on you need to set header fields and http method so IMO it has to be NSMutableURLRequest.

2016-09-18 17:13 UTC, Fawxy commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
`URLRequest` is mutable provided it is not defined as a `let` constant

2016-09-18 17:14 UTC, tomkowz commented on Network/NetworkService.swift
> +            let mutableRequest = NSMutableURLRequest(url: url, cachePolicy: .reloadIgnoringLocalAndRemoteCacheData,
You can extract cache policy and timeout interval before switch and use them in this switch.

2016-09-18 17:19 UTC, tomkowz commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
How is that possible? documentation clearly says `allHTTPHeaderFields` is read-only: https://developer.apple.com/reference/foundation/nsurlrequest/1418477-allhttpheaderfields

`httpMethod` too.

2016-09-18 17:26 UTC, Fawxy commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
Sure - give me a sec to fork :) there are a bunch of other changes needed too for the final release of Xcode 8

2016-09-18 17:35 UTC, tomkowz commented on Network/NetworkService.swift
> +    private func makeQuery(for url: URL, params: [String: AnyObject], type: QueryType) -> NSMutableURLRequest? {
Cool, thank you!

2016-09-18 23:46 UTC, tomkowz commented
Hey @darthpelo. Thank you for your work again. Great job! We took your piece of code to the https://github.com/tomkowz/NetworkLayerExample/pull/3 PR and improved it a bit.

2016-09-18 23:46 UTC, closed without merging

2016-09-19 10:02 UTC, darthpelo commented
@tomkowz glad to help you :)